import java.util.InputMismatchException;
import java.util.Random;
import java.util.Scanner;

/**
 * GuessTheNumber class generates a random number between 1 and 100 (inclusive) and allows the user to take as many guesses as possible to get the number (also keeping track of invalid inputs and the number of attempts to get it right).
 */
public class GuessTheNumber {
    /**
     * Main function of the program. Runs the playGame method and initializes variables used.
     * @param args String array that holds command line arguments when the program is executed.
     */
    public static void main(String[] args){
        // Create a random number generator
        Random random = new Random();

        // Generate a random number between 1 and 100
        int targetNumber = random.nextInt(100) + 1; // random number between 1–100

        playGame(targetNumber);
    }

    /**
     * Continuously asks the user to input a guess and uses try and catch to check if inputs are integers.
     * Iterates over and over again using a while loop that is based on if the user guessed the number or not.
     * Guessed is initially set to zero and updates once the value is guessed correctly.
     * Prints out hints depending on if the user's guess is above or below the targetNumber.
     * Once the user guesses the number, the method prints out the correct number and how many attempts the user used to get it.
     * @param targetNumber the number that the user is trying to guess. Randomly generated by the random class between 1 and 100.
     */
    public static void playGame(int targetNumber) {
        // TODO: Implement the method
        int guessed = 0;
        int attempts = 0;
        System.out.println("Welcome to 'Guess the Number'!");
        System.out.println("I'm thinking of a number between 1 and 100.");
        Scanner scan = new Scanner(System.in);
        while (guessed == 0)
        {
            System.out.print("Enter your guess: ");
            int guess;
            try
            {
                guess = scan.nextInt();
            }
            catch (InputMismatchException e)
            {
                System.out.println("Error: Invalid input. Please enter a number between 1 to 100.");
                scan.next();
                continue;
            }

            if (guess <= 100 && guess >= 1)
            {
                if (guess > targetNumber)
                {
                    attempts++;
                    System.out.println("Too high! Try again.");
                }
                else if (guess < targetNumber)
                {
                    attempts++;
                    System.out.println("Too low! Try again.");
                }
                else if (guess == targetNumber)
                {
                    System.out.println("Congratulations! You guessed it!");
                    attempts++;
                    guessed++;
                }
            }
            else
            {
                System.out.println("Error: Invalid input. Please enter a number between 1 and 100.");
            }

        }
        System.out.println("The number was " + targetNumber + ".");
        System.out.println("You took " + attempts + " attempts.");
    }
}
